### ISSUE TITLE
Having Issues with The Project.

### ISSUE THREAD

**Issue by ASparkOfFire** [DruidMech/UE4-CPP-Shooter-Series#2]
Hello thanks for this Invaluable Series. Really Loving It So far. Just finished the Reloading section and I am facing some Issues. 

1) Sometimes when I am Switching Guns the gun stays in air and Belica becomes Unarmed and the Error Log Shows Warning "Attempting to move fully simulated skeletal mesh".

^ Covered in Lecture 180

2) The gun will reload on pressing the R button even when the Magazine is Full.

^ The above is also covered in Later Sections

**Comment by DruidMech** [comment]
Hello! Thanks for reaching out. Could you post this in the Udemy Q & A? I
prefer to answer questions there so other students can benefit from seeing
the solution.
Stephen

**Comment by ASparkOfFire** [comment]
Sure Thing!

**Comment by ASparkOfFire** [comment]
EDIT : Covered in later sections :D
